# Generated by Django 5.2 on 2026-09-16 11:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=120)),
                ('side', models.CharField(choices=[('BUY', 'Nákup'), ('SELL', 'Prodej')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.account')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'symbol'), name='unique_account_symbol')],
            },
        ),
    ]
